# desired.yml
kind: infrop.caos.ch/Infrop
desiredVersion: v1
desired:
  clusters:
    ops:
      kind: infrop.caos.ch/KubernetesCluster
      desiredVersion: v1alpha5
      desired:
        version: "v1.15.1"
        controlplane:
          updatesDisabled: true
          provider: google
          nodes: 1
          pool: standard
        workers:
          belgium:
            updatesDisabled: false
            provider: google
            nodes: 2
            pool: highmem
  providers:
    google:
      kind: infrop.caos.ch/GCEProvider
      desiredVersion: v1
      desired:
        project: caos-240809
        region: europe-west1
        zone: europe-west1-b
        pools:
          standard:
            minCPUCores: 2
            minMemoryGB: 1
            storageGB: 15
          highmem:
            minCPUCores: 2
            minMemoryGB: 1
            storageGB: 15
          highcpu:
            minCPUCores: 2
            minMemoryGB: 1
            storageGB: 15

# current.yml

###############################################
######    GENERATED FILE, DO NOT EDIT    ######
###############################################
kind: infrop.caos.ch/Infrop
currentVersion: v1
current:
  status: maintaining
  clusters:
    ops:
      kind: infrop.caos.ch/KubernetesCluster
      currentVersion: v1
      current:
        status: maintaining
        providers:
          google:
            kind: infrop.caos.ch/GCEProvider
            currentVersion: v1
            current: dag
        computes:
          k8sops-standard-64645234234:
            status: running
            metadata:
              tier: controlplane
              provider: google
              pool: standard
            software:
              kind: nodeagent.caos.ch/NodeAgent
              desiredVersion: v1
              desired:
                changesAllowed: false
                rebootEnabled: false
                software:
                  containerruntime: docker-ce
                  kubelet: "v1.15.1:00"
              currentVersion: v1
              current:
                ready: true
                software:
                  containerruntime: docker-ce
                  kubelet: "v1.15.1:00"
          k8sops-highmem-795687966832:
            status: maintaining
            metadata:
              tier: worker
              group: belgium
              provider: google
              pool: highmem
            software:
              kind: nodeagent.caos.ch/NodeAgent
              desiredVersion: v1alpha5
              desired:
                changesAllowed: true
                rebootEnabled: false
                software:
                  containerruntime: docker-ce
                  kubelet: "v1.16.0:00"
              currentVersion: v1
              current:
                ready: false
                software:
                  containerruntime: docker-ce
                  kubelet: "v1.15.1:00"      
          k8sops-highmem-208564835876:
            status: maintaining
            metadata:
              tier: worker
              group: belgium
              provider: google
              pool: highmem
            software:
              kind: nodeagent.caos.ch/NodeAgent
              desiredVersion: v1
              desired:
                changesAllowed: true
                rebootEnabled: true
                software:
                  containerruntime: docker-ce
                  kubelet: "v1.15.1:00"
