apiVersion: v1
kind: Pod
metadata:
  name: backup
  namespace: caos-zitadel
spec:
  dnsPolicy: ClusterFirst
  containers:
    - command:
        - /bin/bash
        - -c
        - while true; do sleep 30; done;
          #- /scripts/backup.sh bucket caos-backups-test adminapi /cockroach /secrets/sa.json /cockroach/cockroach-certs
          #&& /scripts/backup.sh
          #bucket caos-backups-test auth /backups && /scripts/backup.sh bucket
          #caos-backups-test authz /backups && /scripts/backup.sh bucket caos-backups-test
          #eventstore /backups && /scripts/backup.sh bucket caos-backups-test management
        #/backups && /scripts/backup.sh bucket caos-backups-test notification
        #/backups &&
      image: docker.pkg.github.com/caos/orbos/crbackup:zitadel
      imagePullPolicy: Always
      name: bucket
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /cockroach/cockroach-certs
          name: client-certs
        - mountPath: /cockroach/cockroach-certs-root
          name: client-certs-root
        - mountPath: /secrets/sa.json
          name: serviceaccountjson
          subPath: serviceaccountjson
  imagePullSecrets:
    - name: public-github-packages
  volumes:
    - name: client-certs
      secret:
        defaultMode: 256
        secretName: cockroachdb.client.authz
    - name: client-certs-root
      secret:
        defaultMode: 256
        secretName: cockroachdb.client.root
    - name: serviceaccountjson
      secret:
        defaultMode: 420
        secretName: backup-serviceaccountjson

  #cockroach.sh sql --certs-dir=/cockroach/cockroach-certs --host=cockroachdb-public:26257 --database=eventstore < /tmp/es.dump