apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: orbiter
build:
  artifacts:
  - image: eu.gcr.io/caos-240809/orbos
    context: .
    custom:
      buildCommand: DEBUG=true ./skaffold/build.sh
deploy:
  kubectl:
    manifests:
    - skaffold/orbiter-deployment.yml
    - skaffold/orbiter-service.yml
    - skaffold/boom-deployment.yml
    - skaffold/boom-service.yml
