kind: orbiter.caos.ch/Orb
version: v0
clusters:
  k8s:
    kind: orbiter.caos.ch/KubernetesCluster
    version: v0
    spec:
      controlplane:
        nodes: 3
        pool: standard
        provider: gce
        updatesdisabled: false
      networking:
        dnsdomain: cluster.orbitertest
        network: calico
        podcidr: 100.127.224.0/20
        servicecidr: 100.126.4.0/22
      versions:
        kubernetes: v1.17.0
        orbiter: v0.15.2
        boom: v0.9.19
      workers:
      - nodes: 2
        pool: highmem
        provider: gce
        updatesdisabled: false
      - nodes: 2
        pool: highcpu
        provider: gce
        updatesdisabled: false
providers:
  gce:
    kind: orbiter.caos.ch/GCEProvider
    version: v1
    spec:
      verbose: false
      project: caos-240809
      region: europe-west6
      zone: europe-west6-b
      pools:
        standard:
          osimage: projects/centos-cloud/global/images/centos-7-v20200429
          preemptible: true
          mincpucores: 2
          minmemorygb: 5
          storagegb: 15
        highmem:
          osimage: projects/centos-cloud/global/images/centos-7-v20200429
          preemptible: false
          mincpucores: 2
          minmemorygb: 10
          storagegb: 15
        highcpu:
          osimage: projects/centos-cloud/global/images/centos-7-v20200429
          preemptible: false
          mincpucores: 4
          minmemorygb: 5
          storagegb: 15
    loadbalancing:
      kind: orbiter.caos.ch/DynamicLoadBalancer
      version: v1
      spec:
        masters:
        - transport:
          - name: kubeapi
            whitelist: [ 0.0.0.0/0 ]
            destinations:
            - pool: masters
              port: 6443
              healthchecks:
                code: 200
                path: /healthz
                protocol: https
        workers:
        - whitelist: [ 0.0.0.0/0 ]
          transport:
          - name: httpsingress
            whitelist: [ 0.0.0.0/0 ]
            destinations:
            - healthchecks:
                protocol: https
                path: /ambassador/v0/check_ready
                code: 200
              port: 30443
              pool: workers
          - name: httpingress
            whitelist: [ 0.0.0.0/0 ]
            destinations:
            - healthchecks:
                protocol: http
                path: /ambassador/v0/check_ready
                code: 200
              port: 30080
              pool: workers
