name: e2e
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 22 * * *'
jobs:
  test:
    name: Test ORBOS on StaticProvider
    runs-on: self-hosted
    steps:
      - name: Source Checkout
        id: source-checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Clone
        id: release
        shell: bash
        run: |
          whoami
          git clone https://github.com/caos/orbos && cd orbos
          git checkout chore
          go run ./cmd/chore/e2e/*.go