name: Release
on:
  push:
    branches:
      - master
jobs:
  release-orbiter:
    name: Release Orbiter
    runs-on: ubuntu-18.04
    steps:
      - name: Source Checkout Orbiter
        id: source-checkout-orbiter
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Release Orbiter
        id: release-orbiter
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO111MODULE: on
          CGO_ENABLED: 0
        run: |
          npm install semantic-release@v16.0.2
          export BRANCH=${GITHUB_REF##*/}
          export VERSION=$BRANCH
          VERSION="v$(npx semantic-release --dry-run --plugins=@semantic-release/commit-analyzer --analize-commits | grep "The next release version is" | sed -ne 's/.*The\ next\ release\ version\ is\ \([0-9]\+\.[0-9]\+\.[0-9]\+\)$/\1/p')"
          [[ "$VERSION" == "v" ]] && echo "Exiting, as no new version needs to be released" && exit 0

          export IMAGE=docker.pkg.github.com/caos/orbos/orbiter
          export TAG_LATEST=${IMAGE}:latest
          export TAG_VERSION=${IMAGE}:${VERSION}

          go mod download
          mkdir -p ./artifacts
          go run cmd/gen-executables/*.go -version "$VERSION" -commit "${{ github.sha }}" -githubclientid "${{ secrets.GITHUBOAUTHCLIENTID }}" -githubclientsecret "${{ secrets.GITHUBOAUTHCLIENTSECRET }}" --orbctl ./artifacts

          echo "Publishing Orbiter version $VERSION"
          docker login docker.pkg.github.com -u ci -p ${GITHUB_TOKEN}
          docker build --tag ${TAG_LATEST} --tag ${TAG_VERSION} --file ./orbiter.Dockerfile .

          docker push ${TAG_VERSION}
          docker push ${TAG_LATEST}
          npx semantic-release && exit 0
  release-boom:
    name: Release Boom
    runs-on: ubuntu-18.04
    steps:
      - name: Source Checkout Boom
        id: source-checkout-boom
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Release Boom
        id: release-boom
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install semantic-release@v16.0.2
          export BRANCH=${GITHUB_REF##*/}
          export VERSION=$BRANCH
          VERSION="v$(npx semantic-release --dry-run --plugins=@semantic-release/commit-analyzer --analize-commits | grep "The next release version is" | sed -ne 's/.*The\ next\ release\ version\ is\ \([0-9]\+\.[0-9]\+\.[0-9]\+\)$/\1/p')"
          [[ "$VERSION" == "v" ]] && echo "Exiting, as no new version needs to be released" && exit 0

          export IMAGE=docker.pkg.github.com/caos/orbos/boom
          export TAG_LATEST=${IMAGE}:latest
          export TAG_VERSION=${IMAGE}:${VERSION}

          echo "Publishing Boom version $VERSION"
          docker login docker.pkg.github.com -u ci -p ${GITHUB_TOKEN}
          docker build --tag ${TAG_LATEST} --tag ${TAG_VERSION} --file ./boom.Dockerfile .

          docker push ${TAG_VERSION}
          docker push ${TAG_LATEST}
          npx semantic-release && exit 0