apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: boom
    app.kubernetes.io/instance: boom
    app.kubernetes.io/managed-by: boom.caos.ch
    app.kubernetes.io/part-of: orbos
  name: boom
  namespace: caos-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: boom
      app.kubernetes.io/instance: boom
      app.kubernetes.io/part-of: orbos
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: boom
        app.kubernetes.io/instance: boom
        app.kubernetes.io/part-of: orbos
    spec:
      containers:
        - args:
            - takeoff
            - boom
            - -f
            - /secrets/orbconfig
          image: eu.gcr.io/caos-240809/orbos
          imagePullPolicy: IfNotPresent
          name: boom
          ports:
            - name: metrics
              containerPort: 2112
            - name: debug
              containerPort: 2345
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /secrets
              name: orbconfig
              readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: gcr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: boom
      serviceAccountName: boom
      terminationGracePeriodSeconds: 10
      volumes:
        - name: orbconfig
          secret:
            defaultMode: 420
            secretName: caos
